# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('headImage', models.FileField(upload_to=b'upload/headImage/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=30)),
                ('videokeyworld', models.CharField(max_length=30)),
                ('videoclass', models.CharField(max_length=30)),
                ('videodescribe', models.CharField(max_length=30)),
                ('videosource', models.FileField(upload_to=b'upload/video/')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videoShare.User')),
            ],
        ),
    ]
